# Generated by Django 3.0.2 on 2020-03-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Person Name')),
                ('age', models.IntegerField()),
                ('RBC_Count', models.IntegerField(blank=True, null=True)),
                ('Platelets', models.IntegerField(blank=True, null=True)),
                ('Neutrofils', models.IntegerField(blank=True, null=True)),
                ('Basofils', models.IntegerField(blank=True, null=True)),
                ('glucose', models.FloatField(default=None)),
                ('bloodpressure', models.FloatField(default=None)),
                ('skinthickness', models.FloatField(default=None)),
                ('insulin', models.FloatField(default=None)),
                ('bmi', models.FloatField(default=None)),
                ('maxrate', models.FloatField(default=None)),
                ('sex', models.CharField(choices=[('F', 'Femlae'), ('M', 'Male'), ('O', 'Other')], default=None, max_length=128)),
                ('marital_status', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default=None, max_length=128)),
                ('cholestrol', models.FloatField(default=None, max_length=120, verbose_name='cholestoral in mg/dl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
